#!/usr/bin/expect -f

# Based on https://github.com/zimfw/zimfw/wiki/Speed
# Usage: ./speedtest {zsh|bash}

set shell [lindex $argv 0]
set wd [file tail [pwd]]
set c0 [clock microseconds]
spawn -noecho $shell -li
expect {
  -re {\e](?:[0127]|1337);.*?(?:\a|\e\\)} { exp_continue } ; # match escape sequences to be ignored
  $wd { send_error "[expr [clock microseconds] - $c0]\n" } ; # match working dir at prompt
  timeout { exit 1 }
}
sleep 1
send "exit\r"
